<a href="https://colab.research.google.com/github/garymontes/curso-python/blob/main/practica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
numeros=np.diag([1,2,3,4,5,6,7,8])
print(numeros)

[[1 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 5 0 0 0]
 [0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 8]]


In [ ]:
eye_matrix.shape

(3, 3)

In [ ]:
eye_matrix.dtype

dtype('float64')

In [ ]:
data1=[9,5.8,0,11,986]
a=np.array(data1)

In [ ]:
print(a)

[  9.    5.8   0.   11.  986. ]


In [ ]:
a

array([  9. ,   5.8,   0. ,  11. , 986. ])

In [ ]:
data2=[[1,2,3,4],[5,6,7,8]]
b=np.array(data2)

In [ ]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 4)

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.empty((3,2,2))

array([[[3.09455750e-316, 4.24399163e-314],
        [6.57818695e-313, 2.54639495e-313]],

       [[3.14668394e-316, 3.21142670e-322],
        [3.09762085e-316, 6.77537605e-310]],

       [[5.31673923e-317, 5.31785384e-317],
        [5.31683409e-317, 5.31161280e-317]]])

In [ ]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
tup=(5,7,2,0)

In [ ]:
arr1=np.array([1,2,3,4], dtype=np.float64)
arr2=np.array([1,2,3,4], dtype=np.int32)
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])


In [ ]:
f=arr*arr
print(f)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


In [ ]:
arr-arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
arr+arr

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [ ]:
1/arr

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [ ]:
arr2=np.array([[0,4,1,5,9],[7,2,12,13,3]])
arr2

array([[ 0,  4,  1,  5,  9],
       [ 7,  2, 12, 13,  3]])

In [ ]:
arr2>arr

array([[False,  True, False,  True,  True],
       [ True, False,  True,  True, False]])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [ ]:
arr[0:2]=1
arr

array([ 1,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr_slice[1]=12345
arr

array([    1,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
arr_slice[:]=64
arr

array([ 1,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d.shape

(3, 3)

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d[2]

array([7, 8, 9])

In [ ]:
arr2d[1][2]

6

In [ ]:
arr2d[0,0]

1

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8,
9], [10, 11, 12]]])
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])