In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [4]:
a2=np.array([0,1,2,3,4,5,6,7,8,9])
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
a3=np.array([[0,1,2],[3,4,5]])
print(a3)

[[0 1 2]
 [3 4 5]]


In [6]:
a4=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
np.sum(a4, axis=0)

array([ 9, 12, 15])

In [8]:
np.sum(a4,axis=1)

array([ 3, 12, 21])

# Creación de arreglo vacio 2x2

In [10]:
a5=np.empty([2,2],dtype=int)
a5[0,0]=10
a5[0,1]=20
a5[1,0]=30
a5[1,1]=40
print(a5)

[[10 20]
 [30 40]]


In [11]:
a6=np.zeros([2,2])
print(a6)

[[0. 0.]
 [0. 0.]]


In [12]:
a7=np.ones([2,2])
print(a7)

[[1. 1.]
 [1. 1.]]


In [13]:
a8=np.full([2,2],5)
print(a8)

[[5 5]
 [5 5]]


In [14]:
print(a3)
print(f'Las dimensiones de la matriz es:{a4.shape}')

[[0 1 2]
 [3 4 5]]
Las dimensiones de la matriz es:(3, 3)


In [15]:
print(f'La lista es: {a2}')
print(f'El número máximo es: {a2.max()}')
print(f'La posición del número máximo es: {a2.argmax()}')
print(f'El número minimo es: {a2.min()}')
print(f'La posisción del número minimo es: {a2.argmin()}')

La lista es: [0 1 2 3 4 5 6 7 8 9]
El número máximo es: 9
La posición del número máximo es: 9
El número minimo es: 0
La posisción del número minimo es: 0


In [16]:
print(f'La suma de la lista es: {a2.sum()}')
print(f'La media de la lista es: {a2.mean()}')

La suma de la lista es: 45
La media de la lista es: 4.5


In [17]:
a9=np.array([10,-2,5,-1,20])
print(a9)
condicion=a9<0
a10=np.where(condicion,0,a9)
print(a10)

[10 -2  5 -1 20]
[10  0  5  0 20]


In [18]:
a11=np.array([[1,2,3],[4,5,6]])
print(a11)

[[1 2 3]
 [4 5 6]]


In [19]:
print(a11[:,0:2])

[[1 2]
 [4 5]]


In [20]:
print(a11[1,1])
print(a11[1][1])
print(a11[1,2])

5
5
6


In [21]:
a12=np.array([22,24,23,25,26,20])
print(f'La temperatura es: {a12}')
print(f'La temperatura máxima es: {a12.max()}')
print(f'La temperatura minima es: {a12.min()}')
print(f'La temperatura media es: {a12.mean()}')

La temperatura es: [22 24 23 25 26 20]
La temperatura máxima es: 26
La temperatura minima es: 20
La temperatura media es: 23.333333333333332
